name: test-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: "h1-h1-passthrough"
      TEST_ROOT: "tests"
    steps:
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Write values to outputs
      id: write
      run: |
        echo "::set-output name=vm-name::bal-perf-vm-`echo ${TEST_NAME} | tr '_' ' '`-${{ GITHUB.RUN_NUMBER }}"
    - name: Test AZ CLI Command
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az vm create --resource-group "${{ secrets.CLUSTER_RESOURCE_GROUP }}"  --name "${{ steps.write.outputs.vm-name }}"  --admin-username "${{ secrets.VM_USER }}" --admin-password "${{ secrets.VM_PWD }}" --location  eastus \
          --image "Canonical:UbuntuServer:18.04-LTS:latest"   